Iter2
AlexCorn999/bonus-system pull request #2
Opened 2023-10-08 08:19 UTC by AlexCorn999

2023-10-13 18:13 UTC, popoffvg requested changes

2023-10-13 18:13 UTC, popoffvg commented on internal/domain/bonuses.go
> +	Bonuses  float32 `json:"current"`
Операции с денежными единицами следует выполнять с помощью чисел с фиксированной точностью (https://github.com/shopspring/decimal). При арифметических операциях float может давать неправильный результат в дробной части, что критично для систем работающих с деньгами.
Ошибка в копейках может привести к юридическим проблемам

2023-10-13 18:13 UTC, popoffvg commented on internal/repository/bonuses.go
> +		return err
нужно оборачивать ошибки, пришедшие не из нашего приложения  иначе будет не понятно где возникла ошибка

2023-10-13 18:13 UTC, popoffvg commented on internal/service/bonuses.go
> +	if sum >= with.Bonuses {
При || отправке нескольких заказов возможно не выполнение этого условия и уход в минус

2023-10-13 18:13 UTC, popoffvg commented on internal/service/bonuses.go
> +	withdrawals, err := b.repo.Withdrawals(userID)
Нужно добавлять пажинацию для данных, которые не является справочными и коллекция растет при использовании системы

2023-10-13 18:13 UTC, popoffvg commented on internal/repository/bonuses.go
> +func (s *Storage) Withdrawals(userID int64) ([]domain.Withdraw, error) {
В сигнатуре должен быть контекст, вместе с которым будет выполнен запрос

2023-10-13 18:13 UTC, popoffvg commented on internal/service/user.go
> +		if errors.Is(err, sql.ErrNoRows) {
Слой сервисов не должен зависеть от sql, ошибку нужно оборачивать на более низком уровне

2023-10-13 18:13 UTC, popoffvg commented on internal/transport/orders.go
> +		if errors.Is(err, domain.ErrAlreadyUploadedByThisUser) {
Лучше не использовать else if при таких лесенках. 
Со switch или if {return} будет наглдляднее
```go
if errors.Is(err, domain.ErrAlreadyUploadedByAnotherUser) {
 			logError("orderUploading", err)
 			w.WriteHeader(http.StatusConflict)
 			return
 		}
if errors.Is(err, domain.ErrIncorrectOrder) {
 			logError("orderUploading", err)
 			w.WriteHeader(http.StatusUnprocessableEntity)
 			return
 		}
```

2023-10-13 18:13 UTC, popoffvg commented on internal/transport/scoringsystem.go
> +		s.logger.Info("scoringSystem - another error")
Ошибку нужно логгировать, уровень лога должен быть ошибка. Иначе будет непонятно что с системой, нужно ли ее чинить. По уровню инфо кажется что нет, а это критичный функционал.

2023-10-13 18:13 UTC, popoffvg commented on internal/transport/scoringsystem.go
> +			logError("scoringSystem", err)
return потерял

2023-10-13 18:13 UTC, popoffvg commented on internal/transport/scoringsystem.go
> +	if resp.StatusCode == http.StatusOK {
Со switch было бы нагляднее

2023-10-13 18:13 UTC, popoffvg commented on internal/transport/scoringsystem.go
> +		s.logger.Info("scoringSystem - order not registered")
Постоянно будем обрабатывать один и тот же заказ. 
Если так и задумывалось, то нужен уровень error чтобы начать реагировать на инцидент

2023-10-14 10:38 UTC, AlexCorn999 commented on internal/transport/scoringsystem.go
> +		s.logger.Info("scoringSystem - order not registered")
Это просто информация. Там не задумывается обработка ошибки, так как система расчета бонусов это черный ящик. Я убрал вообще эти логи, чтобы не было лишней информации по каждому запросу. Так как если что то пойдет не так то итак выйдет лог с ошибкой.

2023-10-14 10:39 UTC, AlexCorn999 commented on internal/transport/scoringsystem.go
> +	if resp.StatusCode == http.StatusOK {
Дополнительные логи убрал, поэтому в свиче нет необходимости

2023-10-14 10:40 UTC, AlexCorn999 commented on internal/transport/scoringsystem.go
> +			logError("scoringSystem", err)
Done

2023-10-14 10:42 UTC, AlexCorn999 commented on internal/transport/scoringsystem.go
> +		s.logger.Info("scoringSystem - another error")
Убрал эти ответы. Там система расчета черный ящик и мы можем получать разные статусы от нее.

2023-10-14 10:46 UTC, AlexCorn999 commented on internal/transport/orders.go
> +		if errors.Is(err, domain.ErrAlreadyUploadedByThisUser) {
Done

2023-10-14 10:59 UTC, AlexCorn999 commented on internal/repository/bonuses.go
> +func (s *Storage) Withdrawals(userID int64) ([]domain.Withdraw, error) {
Done

2023-10-14 11:11 UTC, AlexCorn999 commented on internal/repository/bonuses.go
> +func (s *Storage) Withdrawals(userID int64) ([]domain.Withdraw, error) {
Добавил контексты во все запросы бд

2023-10-14 11:18 UTC, AlexCorn999 commented on internal/service/bonuses.go
> +	withdrawals, err := b.repo.Withdrawals(userID)
Имеется в виду ограничение выводных данных информации по кол-ву? Так как коллекция может быть огромной и нудна свежая информация?

2023-10-14 11:22 UTC, AlexCorn999 commented on internal/service/bonuses.go
> +	withdrawals, err := b.repo.Withdrawals(userID)
Добавил с ограничением на 10 записей

2023-10-14 11:47 UTC, AlexCorn999 commented on internal/repository/bonuses.go
> +		return err
Done

2023-10-14 13:21 UTC, AlexCorn999 commented on internal/domain/bonuses.go
> +	Bonuses  float32 `json:"current"`
оставил поля float32, а сами вычисления в decimal

2023-10-14 13:23 UTC, AlexCorn999 commented on internal/service/bonuses.go
> +	if sum >= with.Bonuses {
увидел, что дублируется снизу. Поправил

2023-11-01 10:27 UTC, popoffvg approved these changes

2023-11-01 10:29 UTC, merged